name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  super-lint:
    # Name the Job
    name: Run project
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    # change machine to windows
#    runs-on: windows-latest
    steps:
      # Copy project through checkout
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '11'
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: make install

      - name: Install Code Climate reporter
        run: |
          export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
          sudo curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          sudo chmod +x ./cc-test-reporter

      - name: Upload coverage information
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_KEY }}
        run: |
          make reports
          ./cc-test-reporter format-coverage build/reports/jacoco/test/jacocoTestReport.xml -t jacoco
#          sudo ./cc-test-reporter after-build -r $CC_TEST_REPORTER_ID -t jacoco
